### ISSUE TITLE
Install phyx via conda

### ISSUE THREAD

**Issue by vmikk** [FePhyFoFum/phyx#60]
Hello!
Thanks a lot for `phyx`, it looks very promising!
However the installation instructions may seem a bit scary for some users.
Do you plan to distribute `phyx` via [conda](https://conda.io/docs/) (e.g., through [bioconda](https://bioconda.github.io/) channel)? It's quite popular now and allows to easily handle package dependencies and update the software.

With best regards,
Vladimir

**Comment by blackrim** [comment]
That looks cool! Haven't looked into it but will do so and update this issue when it is done. Thanks

**Comment by druvus** [comment]
I started to generate a bioconda recipe for phyx but run into some issues. You can find the current PR here:  bioconda/bioconda-recipes#4539 
I managed to get it building on the linux image that is used by bioconda but forgot something in the recipe. I will try to come back and fix it later during the week but you might have a better understanding of the error.

**Comment by nickloman** [comment]
I'd also be keen to see this building on Conda.

**Comment by blackrim** [comment]
Cool. I will resurrect this starting with the PR

**Comment by druvus** [comment]
@blackrim I have a working recipe for phyx locally but it needs a rebuild of nlopt using cxx. I opened PR at  conda-forge/nlopt-feedstock#12. You are probably more familiar with nlopt to comment issues raised by @jschueller that is maintainer of the nlopt recipe.

**Comment by jschueller** [comment]
You dont need to enable cxx. For nlopt what it really does is enable the algorithm that is written in c++, but the api of nlopt remains C. The C++ interface for nlopt exists but is header-only and is not related to the with-cxx option. What you just have to do is tell phyx to link to nlopt instead of nlopt_cxx, here is the relevant phyx configure.ac line:
```
AC_SEARCH_LIBS([nlopt_urand], [nlopt_cxx], [have_nlopt=yes], [have_nlopt=no], [-lstdc++])
```
This phyx nlopt detection has to be improved, first look for nlopt, then nlopt_cxx+lstdc++.

**Comment by blackrim** [comment]
Thanks @jschueller and @druvus we will have a look at this and hopefully deal with it in the next day or two.

**Comment by jfwalker** [comment]
Thanks @jschueller and @druvus ! I tried taking a look, is the edit needed as trivial as changing the line to: 
```
AC_SEARCH_LIBS([nlopt_urand], [nlopt], [have_nlopt=yes], [have_nlopt=no], [-lstdc++])
```
or is there more that needs to be done? Sorry I don't have muct familiarity with conda. Thanks!

**Comment by blackrim** [comment]
@jfwalker thanks but I think I have a better general solution. Pushing in one sec

**Comment by blackrim** [comment]
OK, I believe this has remedied teh situation. No more nlopt_cxx in linking or configure 6372057277df00c34bc2d6d71ffb29402a70256b
@druvus and @jschueller

**Comment by druvus** [comment]
@blackrim I have an open PR to build phyx that pass the tests: bioconda/bioconda-recipes#9119

I am currently using the latest commit but would it be possible to get a new tagged release that I could refer to?

**Comment by josephwb** [comment]
We are planning on a minor release update early next week.

**Comment by jamie-arcc** [comment]
Is there any update on this?  This would be a requisite for https://github.com/FePhyFoFum/PyPHLAWD/issues/27 as well

**Comment by josephwb** [comment]
Sorry this has dragged for so long. Let's get it closed. I have no knowledge of conda. What do you require from us? We _should_ make a new release, as a few bugs have been fixed since the last one. Can you do this @blackrim?

**Comment by jamie-arcc** [comment]
bump

**Comment by josephwb** [comment]
I don't have the faintest clue what is needed on this from our side (sorry: no experience with conda whatsoever). We do have a recent release [here](https://github.com/FePhyFoFum/phyx/releases/tag/v1.01). Is there something else?

**Comment by blackrim** [comment]
Back here, but still don't know what we need to do to get this through.

**Comment by druvus** [comment]
Finally got back to this and phyx is now available through Bioconda.

**Comment by josephwb** [comment]
@druvus Sweet, thanks! So, we can close this?

**Comment by druvus** [comment]
Yes, please close it. Upcoming updates will be handled by the Bioconda bot.
